### PR TITLE
Start adding regression testing for bare metal emulation

### PR DESCRIPTION
**Pull request by tkchia**

### CODE REVIEW

**Comment by tkchia** [comment]
* The latest commit (https://github.com/jart/blink/pull/47/commits/aa24f3c595fb765a41885c6dacc65125db1a650e) also fixes a bug in the `les` opcode emulation, which I had admittedly introduced in my earlier PR (https://github.com/jart/blink/pull/30).
* Currently, the bare metal tests invoke `int3` on failure, and invokes `syscall` on success.  This works for now, though I am not sure if it is the best arrangement (particularly since I understand that `syscall` is not really a valid instruction outside of long mode).
* I am not sure why the macOS tests are failing.

Thank you!

**Comment by trungnt2910** [comment]
> I am not sure why the macOS tests are failing.

```
I2023-01-21T11:04:36.030512:blink/jit.c:247:25583 ran out of jit memory
I2023-01-21T11:04:36.410798:blink/jit.c:247:25653 ran out of jit memory
I2023-01-21T11:04:40.700599:blink/jit.c:247:25608 ran out of jit memory
I2023-01-21T11:04:40.865301:blink/jit.c:247:25605 ran out of jit memory
```

A similar error happens at #43 that doesn't have anything to do with Blink on macOS.
You should try `git commit --amend` and force push to force the PR workflows to run again.

If needed, I might make a PR to guard this step with [the retry action](https://github.com/nick-fields/retry).

**Review by jart — APPROVED** [review]
Thank you!

**Comment by jart** [comment]
MacOS has been flaky. I'll probably disable it soon.

**Comment by jart** [comment]
Oh if it's possible to automatically retry MacOS that'd be gread.

**Pull request merged**
